apiVersion: v2
# StackStorm version which refers to Docker images tag
appVersion: "3.8"
name: stackstorm-ha
version: 1.1.5
description: StackStorm K8s Helm Chart, optimized for running StackStorm in HA environment.
home: https://stackstorm.com/
icon: https://landscape.cncf.io/logos/stack-storm.svg
source:
  - https://github.com/stackstorm/stackstorm-k8s
keywords:
  - st2
  - stackstorm
  - devops
  - SRE
  - automation
  - chatops
  - event-driven
  - auto-remediation
  - IFTTT
  - HA
maintainers:
  - name: The StackStorm Authors
    email: info@stackstorm.com
    url: https://github.com/StackStorm
details:
  This Helm chart is a fully installable app that codifies StackStorm cluster deployment optimized for HA and K8s environment.
  MongoDB-HA is deployed using the MongoDB Community Operator (must be pre-installed), val-key operator, and rabbitmq operator
 For configuration details please check default values.yaml and README.
dependencies:
  - name: external-dns
    version: 4.0.0
    repository: alias:bitnami-mirror
    condition: external-dns.enabled
  - name: valkey
    version: 0.9.3
    repository: alias:valkey-mirror
    condition: valkey.enabled
