{{- if and .Values.valkey.enabled .Values.valkey.auth.enabled .Values.valkey.auth.usersExistingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-valkey-config
  annotations:
    description: StackStorm Valkey coordination credentials configuration
  labels: {{- include "stackstorm-ha.labels" (list $ "st2") | nindent 4 }}
type: Opaque
stringData:
  st2.valkey.conf: |
    [coordination]
    {{- $valkeySecret := lookup "v1" "Secret" .Release.Namespace .Values.valkey.auth.usersExistingSecret }}
    {{- if $valkeySecret }}
    {{- $passwordKey := default "default-password" .Values.valkey.auth.aclUsers.default.passwordKey }}
    {{- $password := index $valkeySecret.data $passwordKey | b64dec }}
    url = redis://:{{ $password }}@{{ .Release.Name }}-valkey.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:6379
    {{- else }}
    url = redis://{{ .Release.Name }}-valkey.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:6379
    {{- end }}
{{- end }}
